"""
manifest_builder.py — Stage UI-3
==========================================================
Scans visualization_output/ and writes:
    visualization_output/assets/generated_manifest.js

The manifest is read by dashboard.js (window.DASHBOARD_MANIFEST).
It embeds summaryData so the dashboard works fully offline
without any fetch() calls.

ARTIFACT_CATALOG defines every expected file.  The builder
checks which ones exist on disk and sets exists: true/false.
==========================================================
"""

import os
import sys
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

_DIR = os.path.dirname(os.path.abspath(__file__))
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)


# ------------------------------------------------------------------
# Artifact catalog — one entry per expected output file.
# Tuple format: (relative_path_from_vizdash, category, id, title, description)
# relative_path uses forward slashes on all platforms.
# ------------------------------------------------------------------

ARTIFACT_CATALOG: List[tuple] = [
    # ---- 3D Particle Viewers ----
    ("html/particle_3d_temperature.html",  "particleViewer",  "p3d_temp",   "3D Viewer — Temperature",      "Interactive 3D scatter coloured by T_p"),
    ("html/particle_3d_vr.html",           "particleViewer",  "p3d_vr",     "3D Viewer — Radial velocity",  "Interactive 3D scatter coloured by v_r"),
    ("html/particle_3d_vtheta.html",       "particleViewer",  "p3d_vt",     "3D Viewer — v_theta",          "Interactive 3D scatter coloured by v_theta"),
    ("html/particle_3d_qp.html",           "particleViewer",  "p3d_qp",     "3D Viewer — Humidity",         "Interactive 3D scatter coloured by q_p"),
    # Preview PNGs for gallery (generated by particle_preview_builder.py)
    ("png/particle_preview_temperature.png",      "particleViewer", "prev_temp",  "Temperature preview — PNG",    "x-z projection (1200×900, 100 DPI)"),
    ("png/particle_preview_vr.png",               "particleViewer", "prev_vr",    "Radial velocity preview — PNG","x-z projection (1200×900, 100 DPI)"),
    ("report_figures/particle_preview_temperature_300dpi.png", "particleViewer", "prev_temp300", "Temperature preview — 300 DPI", "Report-ready x-z projection"),
    ("report_figures/particle_preview_vr_300dpi.png",          "particleViewer", "prev_vr300",   "Radial velocity preview — 300 DPI", "Report-ready x-z projection"),
    ("png/particle_3d_temperature_preview.png", "particleViewer", "p3d_prev_t",  "3D Temperature preview — PNG", "Legacy matplotlib 3D preview"),
    ("png/particle_3d_vr_preview.png",          "particleViewer", "p3d_prev_vr", "3D Velocity preview — PNG",    "Legacy matplotlib 3D preview"),
    # ---- Particle Animations ----
    ("html/particle_animation_temperature.html", "particleAnimations", "anim_temp", "Animation — Temperature",  "Plotly animated 3D shell (play/pause/slider)"),
    ("html/particle_animation_qp.html",          "particleAnimations", "anim_qp",   "Animation — Humidity",     "Plotly animated 3D shell coloured by q_p"),
    ("html/particle_animation_vr.html",          "particleAnimations", "anim_vr",   "Animation — v_r",          "Plotly animated 3D shell coloured by v_r"),
    ("animations/particle_animation_preview.gif","particleAnimations", "anim_gif",  "GIF preview",              "Static GIF preview of temperature animation"),
    ("animations/particle_animation_preview.png","particleAnimations", "anim_png",  "PNG preview",              "Static PNG preview of particle shell"),
    # ---- Streamfunction ----
    ("html/streamfunction_heatmap_contours.html",          "streamfunction", "sf_html",   "Streamfunction — Interactive", "Plotly heatmap + contour overlay"),
    ("png/streamfunction_heatmap_contours.png",            "streamfunction", "sf_png",    "Streamfunction — PNG",         "Matplotlib heatmap (120 DPI)"),
    ("report_figures/streamfunction_heatmap_contours_300dpi.png", "streamfunction", "sf_300", "Streamfunction — 300 DPI",  "Report-ready 300 DPI figure"),
    ("html/max_abs_psi_vs_time.html",                      "streamfunction", "psi_html",  "max|Ψ| vs time — Interactive", "Plotly line chart"),
    ("png/max_abs_psi_vs_time.png",                        "streamfunction", "psi_png",   "max|Ψ| vs time — PNG",         "Matplotlib line chart (120 DPI)"),
    ("report_figures/max_abs_psi_vs_time_300dpi.png",      "streamfunction", "psi_300",   "max|Ψ| vs time — 300 DPI",     "Report-ready 300 DPI figure"),
    # ---- Meridional Wind ----
    ("html/vtheta_heatmap.html",             "meridionalWind", "vt_html",   "v_theta heatmap — Interactive", "Plotly heatmap"),
    ("png/vtheta_heatmap.png",               "meridionalWind", "vt_png",    "v_theta heatmap — PNG",         "Matplotlib heatmap (120 DPI)"),
    ("report_figures/vtheta_heatmap_300dpi.png","meridionalWind","vt_300",  "v_theta heatmap — 300 DPI",     "Report-ready 300 DPI figure"),
    ("summary/computed_vtheta_grid.csv",     "meridionalWind", "vt_csv",    "v_theta binned grid CSV",       "Computed latitude–altitude grid"),
    # ---- Thermal Diagnostics ----
    ("html/temperature_zones_timeseries.html",           "thermalDiagnostics", "tz_html",  "Temp. zones — Interactive",  "Plotly line chart by latitude zone"),
    ("png/temperature_zones_timeseries.png",             "thermalDiagnostics", "tz_png",   "Temp. zones — PNG",          "Matplotlib chart (120 DPI)"),
    ("report_figures/temperature_zones_timeseries_300dpi.png","thermalDiagnostics","tz_300","Temp. zones — 300 DPI",     "Report-ready 300 DPI figure"),
    ("png/altitude_temperature_profile.png",             "thermalDiagnostics", "atp_png",  "Altitude–T profile — PNG",   "Temperature vs altitude"),
    ("report_figures/altitude_temperature_profile_300dpi.png","thermalDiagnostics","atp_300","Altitude–T profile — 300 DPI","Report-ready 300 DPI figure"),
    ("html/altitude_temperature_profile.html",           "thermalDiagnostics", "atp_html", "Altitude–T profile — Interactive","Plotly scatter (altitude vs temperature)"),
    ("png/simulation_energy.png",            "thermalDiagnostics", "en_png",   "Simulation energy — PNG",    "Kinetic / potential / total energy"),
    ("report_figures/simulation_energy_300dpi.png","thermalDiagnostics","en_300","Simulation energy — 300 DPI","Report-ready figure"),
    # ---- Water Balance ----
    ("html/water_balance_panels.html",       "waterBalance", "wb_html",   "Water balance — Interactive",   "Plotly 4-panel diagnostic"),
    ("png/water_balance_panels.png",         "waterBalance", "wb_png",    "Water balance — PNG",           "Matplotlib multi-panel (120 DPI)"),
    ("report_figures/water_balance_panels_300dpi.png","waterBalance","wb_300","Water balance — 300 DPI",  "Report-ready 300 DPI figure"),
    ("summary/water_balance_summary.json",   "waterBalance", "wb_json",   "Water balance summary JSON",    "Status, error metrics, latest step"),
    # ---- Evaporation & Condensation ----
    ("html/evap_cond_timeseries.html",       "evaporationCondensation", "ec_html",     "Evap/Cond — Interactive",      "Plotly combined diagnostic"),
    ("png/evap_cond_timeseries.png",         "evaporationCondensation", "ec_png",      "Evap/Cond — PNG",              "Combined rates + cumulative"),
    ("report_figures/evap_cond_timeseries_300dpi.png","evaporationCondensation","ec_300","Evap/Cond — 300 DPI",       "Report-ready 300 DPI figure"),
    ("png/evap_cond_rates_only.png",         "evaporationCondensation", "ec_rp",       "Rates only — PNG",             "Instantaneous rates per step"),
    ("report_figures/evap_cond_rates_only_300dpi.png","evaporationCondensation","ec_r300","Rates only — 300 DPI",     "Report-ready 300 DPI figure"),
    ("png/evap_cond_cumulative_only.png",    "evaporationCondensation", "ec_cp",       "Cumulative only — PNG",        "Cumulative totals"),
    ("report_figures/evap_cond_cumulative_only_300dpi.png","evaporationCondensation","ec_c300","Cumulative — 300 DPI","Report-ready 300 DPI figure"),
    ("summary/evap_cond_summary.json",       "evaporationCondensation", "ec_json",     "Evap/Cond summary JSON",       "Latest rates and totals"),
    # ---- Moisture Heatmaps ----
    ("html/humidity_lat_alt_heatmap.html",          "moisture", "hm_html",   "Humidity heatmap — Interactive",    "Plotly q_p lat–alt heatmap"),
    ("png/humidity_lat_alt_heatmap.png",            "moisture", "hm_png",    "Humidity heatmap — PNG",            "q_p binned by lat/alt"),
    ("report_figures/humidity_lat_alt_heatmap_300dpi.png","moisture","hm_300","Humidity heatmap — 300 DPI",     "Report-ready 300 DPI figure"),
    ("html/relative_humidity_heatmap.html",         "moisture", "rh_html",   "Rel. humidity — Interactive",       "Plotly RH heatmap"),
    ("png/relative_humidity_heatmap.png",           "moisture", "rh_png",    "Rel. humidity — PNG",               "RH = q_p / q_sat"),
    ("report_figures/relative_humidity_heatmap_300dpi.png","moisture","rh_300","Rel. humidity — 300 DPI",       "Report-ready 300 DPI figure"),
    ("png/condensation_zones_heatmap.png",          "moisture", "cz_png",    "Condensation zones — PNG",          "Fraction of particles with q_p > q_sat"),
    ("report_figures/condensation_zones_heatmap_300dpi.png","moisture","cz_300","Condensation zones — 300 DPI", "Report-ready 300 DPI figure"),
    ("summary/computed_qp_grid.csv",                "moisture", "qp_csv",    "q_p binned grid CSV",               "Computed latitude–altitude grid"),
    # ---- Validation ----
    ("validation/moisture_balance.csv",                   "validation", "val_wb",    "Moisture balance CSV",               "Copied from simulation output"),
    ("validation/temperature_zones.csv",                  "validation", "val_tz",    "Temperature zones CSV",              "Copied from simulation output"),
    ("validation/evaporation_log.csv",                    "validation", "val_ev",    "Evaporation log CSV",                "Copied from simulation output"),
    ("validation/condensation_log.csv",                   "validation", "val_co",    "Condensation log CSV",               "Copied from simulation output"),
    ("validation/simulation_log.csv",                     "validation", "val_sl",    "Simulation log CSV",                 "Copied from simulation output"),
    ("validation/streamfunction_summary.csv",             "validation", "val_sf",    "Streamfunction summary CSV",         "Copied from simulation output"),
    ("validation/visualization_validation_summary.md",    "validation", "val_vis_md","Visualization validation summary",   "Auto-generated diagnostic summary"),
    ("validation/water_balance_summary.md",               "validation", "val_wb_md", "Water balance summary",              "Water balance status and error metrics"),
    # ---- VTK ----
    ("vtk/particles_step_100000.vtk", "vtk", "vtk_p100k", "VTK particles step 100000",
     "ASCII Legacy VTK for ParaView — generated by Stage UI-4"),
    # ---- Documentation ----
    ("docs/physics_model_report.md",        "documentation", "doc_phys",   "Physics model report",        "Physics documentation Markdown"),
    ("docs/README.md",                      "documentation", "doc_readme", "Project README",               "Top-level project README"),
    ("docs/README_UI_STAGE_2.md",           "documentation", "doc_s2",     "README — Stage UI-2",         "Artifact collection documentation"),
    ("docs/README_UI_STAGE_3.md",           "documentation", "doc_s3",     "README — Stage UI-3",         "Visualization builder documentation"),
    # ---- Summary ----
    ("summary/dashboard_summary.json",      "summary", "dash_sum",   "Dashboard summary JSON",      "Overall generation stats and statuses"),
    ("summary/water_balance_summary.json",  "summary", "sum_wb",     "Water balance summary",        "Status + error metrics"),
    ("summary/evap_cond_summary.json",      "summary", "sum_ec",     "Evap/Cond summary",            "Latest rates and totals"),
    ("summary/computed_vtheta_grid.csv",    "summary", "sum_vt",     "v_theta grid CSV",             "Binned meridional wind grid"),
    ("summary/computed_qp_grid.csv",        "summary", "sum_qp",     "q_p grid CSV",                 "Binned specific humidity grid"),
]

ALL_CATEGORIES = [
    "particleViewer", "particleAnimations", "streamfunction", "meridionalWind",
    "thermalDiagnostics", "moisture", "waterBalance", "evaporationCondensation",
    "validation", "reportFigures", "vtk", "documentation", "summary",
]


# ------------------------------------------------------------------
# Build and write manifest
# ------------------------------------------------------------------

def build_manifest(
    out_dir: str,
    summary_data: Optional[Dict[str, Any]] = None,
    warnings_list: Optional[List[str]] = None,
    verbose: bool = False,
) -> str:
    """
    Scan `out_dir` for existing artifacts, build the manifest dict,
    and write `out_dir/assets/generated_manifest.js`.

    Returns the path to the written file.
    """
    summary_data   = summary_data   or {}
    warnings_list  = warnings_list  or []

    artifacts_by_cat: Dict[str, List[Dict[str, Any]]] = {cat: [] for cat in ALL_CATEGORIES}
    expected_filenames: List[str] = []

    for (rel_path, cat, art_id, title, description) in ARTIFACT_CATALOG:
        full_path = os.path.join(out_dir, rel_path.replace("/", os.sep))
        ext       = Path(rel_path).suffix.lstrip(".")
        filename  = Path(rel_path).name

        # For VTK files, check the file is non-trivial (>200 bytes) and has
        # DATASET + POINTS in the header region (POINT_DATA may be far into
        # the file for large particle sets — don't require it in the first read).
        if ext == "vtk" and os.path.isfile(full_path):
            try:
                file_size = os.path.getsize(full_path)
                if file_size < 200:
                    exists = False
                else:
                    with open(full_path, encoding="ascii", errors="ignore") as _vf:
                        _head = _vf.read(4096)
                    exists = ("DATASET" in _head and "POINTS" in _head
                              and "float" in _head)
            except Exception:
                exists = False
        else:
            exists = os.path.isfile(full_path)

        artifacts_by_cat.setdefault(cat, []).append({
            "id":           art_id,
            "title":        title,
            "category":     cat,
            "type":         ext,
            "filename":     filename,
            "relativePath": rel_path,
            "exists":       exists,
            "description":  description,
        })
        expected_filenames.append(filename)

    # Also scan report_figures/ and add each 300-DPI file found that
    # isn't already catalogued (for forward compatibility)
    catalogued_relpaths = {e[0] for e in ARTIFACT_CATALOG}
    rpt_dir = os.path.join(out_dir, "report_figures")
    if os.path.isdir(rpt_dir):
        for fname in sorted(os.listdir(rpt_dir)):
            rel = f"report_figures/{fname}"
            if rel not in catalogued_relpaths and fname.endswith(".png"):
                artifacts_by_cat["reportFigures"].append({
                    "id":           f"rf_{fname.replace('.', '_')}",
                    "title":        fname.replace("_", " ").replace(".png", ""),
                    "category":     "reportFigures",
                    "type":         "png",
                    "filename":     fname,
                    "relativePath": rel,
                    "exists":       True,
                    "description":  "300 DPI report figure (auto-discovered)",
                })

    # Also scan vtk/ and add any VTK files not already catalogued
    vtk_dir = os.path.join(out_dir, "vtk")
    if os.path.isdir(vtk_dir):
        for fname in sorted(os.listdir(vtk_dir)):
            if not fname.endswith(".vtk"):
                continue
            rel = f"vtk/{fname}"
            if rel not in catalogued_relpaths:
                artifacts_by_cat["vtk"].append({
                    "id":           f"vtk_{fname.replace('.', '_')}",
                    "title":        fname,
                    "category":     "vtk",
                    "type":         "vtk",
                    "filename":     fname,
                    "relativePath": rel,
                    "exists":       True,
                    "description":  "ASCII Legacy VTK for ParaView (auto-discovered)",
                })

    available_count = sum(
        a["exists"]
        for cat_list in artifacts_by_cat.values()
        for a in cat_list
    )
    missing_count = sum(
        not a["exists"]
        for cat_list in artifacts_by_cat.values()
        for a in cat_list
    )

    manifest: Dict[str, Any] = {
        "generatedAt":    _utc_now(),
        "availableCount": available_count,
        "missingCount":   missing_count,
        "isStub":         False,
        "artifacts":      artifacts_by_cat,
        "expected":       expected_filenames,
        "summaryData":    summary_data,
        "buildWarnings":  warnings_list,
    }

    # ---- Write JS file -----------------------------------------------
    assets_dir = os.path.join(out_dir, "assets")
    os.makedirs(assets_dir, exist_ok=True)
    js_path = os.path.join(assets_dir, "generated_manifest.js")

    js_body = json.dumps(manifest, indent=2, default=str, ensure_ascii=False)
    comment = (
        "/* ================================================================\n"
        "   generated_manifest.js\n"
        "   Auto-generated by visualization/build_dashboard.py\n"
        "   Do NOT edit manually — re-run the script to update.\n"
        f"   Generated at: {manifest['generatedAt']}\n"
        f"   Available: {available_count}   Missing: {missing_count}\n"
        "   ================================================================ */\n\n"
    )
    with open(js_path, "w", encoding="utf-8") as fh:
        fh.write(comment)
        fh.write("window.DASHBOARD_MANIFEST = ")
        fh.write(js_body)
        fh.write(";\n")

    if verbose:
        print(f"  [OK] {os.path.relpath(js_path)}"
              f"  available={available_count}  missing={missing_count}")

    return js_path


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_json_summary(path: str) -> Dict[str, Any]:
    """Load a JSON summary file, returning {} on failure."""
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except Exception:  # noqa: BLE001
        return {}
